In [4]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp
print(tf.__version__)

ModuleNotFoundError: No module named 'tensorflow_probability'

In [3]:
!pip install --upgrade tensorflow-probability


244.96s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


Let create a tensor 

In [ ]:
scaler = tf.constant(7)
scaler

print("Checking the number of Dimensions", scaler.ndim)

Checking the number of Dimensions 0


Let create a vector 

In [ ]:
vector1 = tf.constant([1,2,3])
vector2 = tf.constant([[1,2,3]])
vector3 = tf.constant([[[1,2,3]]])

print("Checking the number of Dimensions for Vector1: ", vector1.ndim)
print("Checking the number of Dimensions for Vector2: ", vector2.ndim)
print("Checking the number of Dimensions for Vector3: ", vector3.ndim)



Checking the number of Dimensions for Vector1:  1
Checking the number of Dimensions for Vector2:  2
Checking the number of Dimensions for Vector3:  3


We have seen how to define a scaler and a vector, now let move on to how to define a matrix 

In [ ]:
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print("Checking the number of Dimensions for matrix: ", matrix.ndim)

Checking the number of Dimensions for matrix:  2


The Dimension of a matrix does not refer to the number of separate arrays in the parent array, but rather the number of arrays defined from the parent array in a tree like structure

Now Let assign a data type to this matrix 

In [ ]:
another_matrix = tf.constant([[1. ,2., 3.], [4., 5., 6.]], dtype=tf.float32)
another_matrix


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Now Let Create a Tensor which is simply a multi dimensional array.
So it moves this way Scaler > Vector > Matrix > Tensor

In [ ]:
tensor = tf.constant([
    [[1,2,3], [4,5,6], [7,8,9] ],
    [[10,11,12], [13,14,15], [16,17,18] ],
    [[19,20,21], [22,23,24], [25,26,27] ],
    [[28,29,30], [31,32,33], [34,35,36] ],
    
])
tensor


<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]], dtype=int32)>

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

Now we can create a tensor which is changeable using the  tf variable

In [ ]:
changeable_tensor = tf.Variable([[1,2], [3,4]])
print("Initial Tensor: ",changeable_tensor)


changeable_tensor[0].assign([11,12])
print("Final Tensor: ",changeable_tensor)


Initial Tensor:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
Final Tensor:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[11, 12],
       [ 3,  4]], dtype=int32)>


When we try to change the values of a constant tensor we get an error 

In [ ]:
tensor[0].assign([11,12])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Now Let create a Random Tensor 

In [ ]:
random_1 = tf.random.Generator.from_seed(7)
print(random_1)

random_1 = random_1.normal(shape=(3,2))
print(random_1)

tf.Tensor(
[[-1.3240396   0.28785667]
 [-0.8757901  -0.08857018]
 [ 0.69211644  0.84215707]], shape=(3, 2), dtype=float32)


We can Shuffle so that the inherent order doesn't effect learning

In [ ]:

data = tf.constant([
    [1,2],
    [11,14],
    [15,16]
])
seed = tf.random.set_seed(42)

shuffled_data1 = tf.random.shuffle(data)
shuffled_data2 = tf.random.shuffle(data, seed=seed)

print(shuffled_data1)
print("\n")
print(shuffled_data2)

tf.Tensor(
[[11 14]
 [15 16]
 [ 1  2]], shape=(3, 2), dtype=int32)


tf.Tensor(
[[15 16]
 [ 1  2]
 [11 14]], shape=(3, 2), dtype=int32)


Exercise 5 Random Tensor and Shuffled 

In [ ]:
tensor1  = tf.random.Generator.from_seed(5) #Generate the Tensor
tensor1 = tensor1.normal(shape=(5,5)) # Shape it into 5 rows, 5 columns
tensor1 = tf.random.shuffle(tensor1) # Shuffle the tensor
print("Shuffled Tensor1: ", tensor1)
print("\n")

tensor2  = tf.random.Generator.from_seed(5) #Generate the Tensor
tensor2 = tensor2.normal(shape=(5,5)) # Shape it into 5 rows, 5 columns
tensor2 = tf.random.shuffle(tensor2) # Shuffle the tensor
print("Shuffled Tensor2: ", tensor2)
print("\n")

tensor3  = tf.random.Generator.from_seed(5) #Generate the Tensor
tensor3 = tensor3.normal(shape=(5,5)) # Shape it into 5 rows, 5 columns
tensor3 = tf.random.shuffle(tensor3) # Shuffle the tensor
print("Shuffled Tensor3: ", tensor3)
print("\n")

tensor4  = tf.random.Generator.from_seed(5) #Generate the Tensor
tensor4 = tensor4.normal(shape=(5,5)) # Shape it into 5 rows, 5 columns
tensor4 = tf.random.shuffle(tensor4) # Shuffle the tensor
print("Shuffled Tensor4: ", tensor4)
print("\n")

tensor5  = tf.random.Generator.from_seed(5) #Generate the Tensor
tensor5 = tensor5.normal(shape=(5,5)) # Shape it into 5 rows, 5 columns
tensor5 = tf.random.shuffle(tensor5) # Shuffle the tensor
print("Shuffled Tensor5: ", tensor5)
print("\n")




Shuffled Tensor1:  tf.Tensor(
[[-1.0242516  -0.6544423  -0.29738766 -1.3240396   0.28785667]
 [-0.8757901  -0.08857018  0.69211644  0.84215707 -0.06378496]
 [-0.29604465 -0.21134205  0.01063002  1.5165398   0.27305737]
 [ 0.92800784 -0.6039789  -0.1766927   0.04221033  0.29037967]
 [ 1.0278524   0.27974114 -0.01347923  1.845181    0.97061104]], shape=(5, 5), dtype=float32)


Shuffled Tensor2:  tf.Tensor(
[[ 0.92800784 -0.6039789  -0.1766927   0.04221033  0.29037967]
 [-0.8757901  -0.08857018  0.69211644  0.84215707 -0.06378496]
 [ 1.0278524   0.27974114 -0.01347923  1.845181    0.97061104]
 [-1.0242516  -0.6544423  -0.29738766 -1.3240396   0.28785667]
 [-0.29604465 -0.21134205  0.01063002  1.5165398   0.27305737]], shape=(5, 5), dtype=float32)


Shuffled Tensor3:  tf.Tensor(
[[ 1.0278524   0.27974114 -0.01347923  1.845181    0.97061104]
 [ 0.92800784 -0.6039789  -0.1766927   0.04221033  0.29037967]
 [-0.8757901  -0.08857018  0.69211644  0.84215707 -0.06378496]
 [-1.0242516  -0.6544423 

Other ways to make tensors, the array inputs is the shape [rows, columns]

In [ ]:
ones = tf.ones([5,5])
print(ones)

zeros = tf.zeros([5,5])
print(zeros)


tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


Turn numpay arrays into an array
* First we will generate a range of numbers from 1 to 25 in a list
* Then we will shape it into a tensorflow 5 by 5

In [ ]:
nArray = np.arange(1,26, dtype=np.int32)
print(nArray) 

print("\n")

shaped = tf.constant([nArray], shape=(5,5))
print(shaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5), dtype=int32)


Grabbing Information From A Tensor 

In [ ]:

print("Datatype of every element:", shaped.dtype)
print("Number of dimensions (rank):", shaped.ndim)
print("Shape of tensor:", shaped.shape)
print("Elements along the 0 axis:", shaped.shape[0])
print("Elements along the last axis:", shaped.shape[-1])
print("Total number of elements in our tensor:", tf.size(shaped))
print("Total number of elements in our tensor:", tf.size(shaped).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 2
Shape of tensor: (5, 5)
Elements along the 0 axis: 5
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(25, shape=(), dtype=int32)
Total number of elements in our tensor: 25


Indexing a Tensor 

In [ ]:
shaped
print(shaped)

print("\nFirst 2 Element:", shaped[:2])
print("\nLast 2 Element:", shaped[3:])
print("\n2nd, 3rd, 4th:", shaped[1:4])
print("\nFirst Element:", shaped[0])
print("\nLast Element:", shaped[-1])


tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5), dtype=int32)

First 2 Element: tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)

Last 2 Element: tf.Tensor(
[[16 17 18 19 20]
 [21 22 23 24 25]], shape=(2, 5), dtype=int32)

2nd, 3rd, 4th: tf.Tensor(
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]], shape=(3, 5), dtype=int32)

First Element: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

Last Element: tf.Tensor([21 22 23 24 25], shape=(5,), dtype=int32)


Manipulating Data 

In [ ]:
print("ADD: ", shaped+10)
print("SUB: ", shaped-10)
print("MUL: ", shaped*10)
print("DIV: ", shaped/10)

other_tensor = tf.ones(shape=(5,5), dtype=tf.int32)
total = shaped + other_tensor
print("Total: ",total)

print("Multply to Tensor: ", shaped*shaped)


ADD:  tf.Tensor(
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]], shape=(5, 5), dtype=int32)
SUB:  tf.Tensor(
[[-9 -8 -7 -6 -5]
 [-4 -3 -2 -1  0]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]], shape=(5, 5), dtype=int32)
MUL:  tf.Tensor(
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]], shape=(5, 5), dtype=int32)
DIV:  tf.Tensor(
[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]], shape=(5, 5), dtype=float64)
Total:  tf.Tensor(
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]], shape=(5, 5), dtype=int32)
Multply to Tensor:  tf.Tensor(
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]], shape=(5, 5), dtype=int32)


Reshape the Tensor

In [ ]:
reshaped = tf.reshape(shaped, shape=(5,5))

print("Reshape: ", reshaped)

Reshape:  tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5), dtype=int32)


Change the Datatype of the tensor 

In [ ]:
shaped = tf.cast(shaped, dtype=tf.float32)
shaped

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]], dtype=float32)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
condenser = tf.abs(shaped)
condenser

print("Full Data: ", condenser)
print("Minimum: ", tf.reduce_min(condenser).numpy())
print("Maximum: ", tf.reduce_max(condenser).numpy())
print("Mean: ", tf.reduce_mean(condenser).numpy())
print("Sum: ", tf.reduce_sum(condenser).numpy())





Full Data:  tf.Tensor(
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]], shape=(5, 5), dtype=float32)
Minimum:  1.0
Maximum:  25.0
Mean:  13.0
Sum:  325.0
